#!/usr/bin/bash

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Exit if any commands fail
set -o errexit

echo "* Build blogspam";
go get github.com/jfqd/blogspam-api
cp go/bin/blogspam-api /opt/local/bin/blogspam-api

echo "* Setup blogspam user and group"
groupadd -g 1100 blogspam
useradd -m -s /usr/bin/bash -d /nonexistent -u 1100 -g blogspam blogspam
passwd -N blogspam
passwd -d blogspam

# Clean up
echo "* Cleaning up."
rm /root/customize
rm -rf /root/go

# Prepare image for provisioning
sm-prepare-image -y
